### DISCUSSION TITLE
Can't apply the theme

### DISCUSSION THREAD

**Discussion by darmach** [ChristophCaina/home-assistant-theme-outline-edge#3] [Q&A]
Hi, I installed this theme with hacs, and added to the config as shown below:

```
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
cover: !include shutters.yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: error
  # logs:
    # homeassistant.components.google_assistant.http: debug
    # custom_components.ble_monitor: debug
```
My themes dir is located in 
```
[core-ssh outline]$ pwd
/root/config/themes/outline
[core-ssh outline]$ ls -l
total 24
-rw-r--r--    1 root     root          2565 Jan 12 11:25 HomeAssistant-Default.yaml
-rw-r--r--    1 root     root          3161 Jan 12 11:25 outline-edge-no-borders
-rw-r--r--    1 root     root          3118 Jan 12 11:25 outline-edge-wihtout-shadow.yaml
-rw-r--r--    1 root     root          3311 Jan 12 11:25 outline-edged-with-shadows.yaml
-rw-r--r--    1 root     root          3090 Jan 12 11:25 outline-no-borders.yaml
-rw-r--r--    1 root     root          3057 Jan 12 11:25 outline.yaml
```

It should work after restarting, right? Nothing seem to have changed, and when I go to profile and attempt to chose theme manually it claims that "No themes available". @ChristophCaina am I doing something wrong?
